// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgsQGu6lfwB4CplbF0swMppBkmVvLZZEs',
    appId: '1:816364706362:web:1ef5a8840c1df72e4e3303',
    messagingSenderId: '816364706362',
    projectId: 'onboarding-x-app-tnb',
    authDomain: 'onboarding-x-app-tnb.firebaseapp.com',
    storageBucket: 'onboarding-x-app-tnb.firebasestorage.app',
    measurementId: 'G-NZK6N1BGJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo9WmZ3UmbUPNB95lqxOP-UaV440Z4uco',
    appId: '1:816364706362:android:30822dcdffc0d9db4e3303',
    messagingSenderId: '816364706362',
    projectId: 'onboarding-x-app-tnb',
    storageBucket: 'onboarding-x-app-tnb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfCEJSelludyF9eOdmioCfOPAPQC0_RD0',
    appId: '1:816364706362:ios:8dedb3e6510456644e3303',
    messagingSenderId: '816364706362',
    projectId: 'onboarding-x-app-tnb',
    storageBucket: 'onboarding-x-app-tnb.firebasestorage.app',
    iosClientId: '816364706362-u1akad036lg765qqpn12k57kiq4eh7lg.apps.googleusercontent.com',
    iosBundleId: 'com.example.onboardxTnbApp',
  );
}
